/* Tiny helpers with no dependencies. */

export const key = (x: number, d: number) => x + ',' + d;
export const clamp = (v: number, a: number, b: number) => (v < a ? a : v > b ? b : v);

/* Blend two packed 0xRRGGBB colours. Lives here rather than in materials.ts
   because world generation needs it and materials.ts imports three.js - the
   pure layer must stay pure or the bundle guard's whole premise goes with it. */
export function mixHex(a: number, b: number, t: number) {
  const u = 1 - t;
  const r = ((a >> 16) & 255) * u + ((b >> 16) & 255) * t;
  const g = ((a >> 8) & 255) * u + ((b >> 8) & 255) * t;
  const bl = (a & 255) * u + (b & 255) * t;
  return (Math.round(r) << 16) | (Math.round(g) << 8) | Math.round(bl);
}

/* The seeded hash the whole world is generated from.

   It lived in world.ts, which is correct by subject and wrong by layering: it
   depends on nothing, and anything that wants a reproducible roll has to sit
   after world.ts to reach it. claim.ts needs one and has to be importable by
   state.ts, which world.ts imports. So it moves to the one module that imports
   nothing at all. Same arithmetic, same numbers, and the golden baselines
   prove it: they are generated by this function and were not re-recorded. */
export function rnd(x: number, y: number, p: number) {
  let h = Math.imul(x | 0, 374761393) ^ Math.imul(y | 0, 668265263) ^ Math.imul(p | 0, 1442695041);
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

/* A reproducible stream of rolls from one seed, for the places that need
   several numbers in a row rather than one per cell. Each call advances a
   counter that goes into both coordinates, so successive values are unrelated
   to each other in the way rnd() is over a grid. */
export function stream(a: number, b: number, p: number): () => number {
  let i = 0;
  return () => { i++; return rnd(a + i * 7, b + i * 31, p); };
}
